config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :rooms do
    resources :reservations
  end
  resources :users do
    resources :requests
  end
  get 'admin', to: 'admin#index'
  namespace :admin do
    resources :rooms
    resources :users
    resources :reservations
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validate :date_before
  validate :date_before_start
  validate :not_tuesday
  validates_time :start_date, between: ['9:00am', '10:00pm']
  validates :start_date, uniqueness: { message: 'は他のユーザーが予約しています' }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :same_date

  def date_before
    errors.add(:start_date, "は過去の日付を選択できません") if start_date < Date.today
  end

  def not_tuesday
    errors.add(:start_date, "は火曜日を選択できません") if start_date.tuesday?
  end

  def date_before_start
    errors.add(:end_date, "は開始時以前の日付を選択できません") if end_date <= start_date
  end

  def same_date
    if (start_date.mon != end_date.mon) || (start_date.mday != end_date.mday)
      errors.add(:end_date, "日をまたいでの予約はできません")
    end
  end

  def start_time
    start_date
  end
end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < ApplicationController
  before_action :admin_user

  def index
    @reservations = Reservation.all.order(start_date: "DESC")
    @rooms = Room.all
    @users = User.all
  end

  def destroy
    reservation = Reservation.find(params[:id])
    if current_user.admin?
      reservation.destroy
      redirect_to admin_reservations_path, notice: '予約を削除しました。'
    end
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  def index
    @reservations = Reservation.all
  end

  def new
    @room = Room.find(params[:room_id])
    @reservation = Reservation.new
    @reservations = Reservation.where(room_id: @room.id)
  end

  def create
    @room = Room.find(params[:room_id])
    @reservations = Reservation.where(room_id: @room.id)
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      session[:reservation] = nil
      redirect_to root_path, notice: "予約が完了しました"
    else
      flash[:danger] = @reservation.errors.full_messages
      @reservation = Reservation.new(reservation_params)
      render 'new'
    end
  end

  def edit
  end

  def show
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :room_id, :user_id)
  end
end

app/helpers/admin/reservations_helper.rb
module Admin::ReservationsHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/views/admin/reservations/index.html.erb
<h2>管理画面　予約一覧</h2>
<section class="admin_user_index">
  <table border="1" class="index_table">
    <tr class="user_header">
      <th>ユーザーネーム</th>
      <th>部屋名</th>
      <th>email</th>
      <th>予約日程</th>
      <th>created_at</th>
      <th>削除</th>
    </tr>
    <% @reservations.each do |reservation| %>
      <% @room = @rooms.find_by(id: reservation.room_id) %>
      <% @user = @users.find_by(id: reservation.user_id) %>
      <tr class="admin_reservations">
        <th><%= @user.username %></th>
        <th><%= @room.title %></th>
        <th><%= @user.email %></th>
        <th><%= reservation.start_date.strftime("%m月%d日%H時%M分") %>-<%= reservation.end_date.strftime("%H時%M分") %></th>
        <th><%= reservation.created_at.strftime("20%y年%m月%d日%H時%M分") %></th>
        <th><%= link_to '削除', admin_reservation_path(reservation.id), method: :delete, class: "black" %></th>
      </tr>
    <% end %>
  </table>
</section>