config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :rooms do
    resources :reservations
  end
  resources :users do
    resources :requests
  end
  get 'admin', to: 'admin#index'
  namespace :admin do
    resources :rooms
    resources :users
    resources :reservations
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validate :date_before_start
  validate :date_before
  validate :not_tuesday
  validates_time :start_date, between: ['9:00am', '10:00pm']
  validates :start_date, uniqueness: { message: ':予約開始日は他のユーザーが予約しています' }
  validates :customer_name, presence: true
  validates :email, presence: true
  validates :phone_number, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  def date_before
    errors.add(:start_date, ":予約開始日は過去の日付を選択できません") if start_date < Date.today
  end

  def date_before_start
    errors.add(:end_date, ":予約終了時は開始時以前の日付を選択できません") if end_date <= start_date
  end

  def not_tuesday
    errors.add(:start_date, ":予約開始日は火曜日を選択できません") if start_date.tuesday?
  end

  def start_time
    start_date
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validate :date_before
  validate :date_before_start
  validate :not_tuesday
  validates_time :start_date, between: ['9:00am', '10:00pm']
  validates :start_date, uniqueness: { message: 'は他のユーザーが予約しています' }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :same_date

  def date_before
    errors.add(:start_date, "は過去の日付を選択できません") if start_date < Date.today
  end

  def not_tuesday
    errors.add(:start_date, "は火曜日を選択できません") if start_date.tuesday?
  end

  def date_before_start
    errors.add(:end_date, "は開始時以前の日付を選択できません") if end_date <= start_date
  end

  def same_date
    if (start_date.mon != end_date.mon) || (start_date.mday != end_date.mday)
      errors.add(:end_date, "日をまたいでの予約はできません")
    end
  end

  def start_time
    start_date
  end
end

app/models/room.rb
class Room < ApplicationRecord
  attachment :room_image
  has_many :reservations, dependent: :destroy
  has_many :requests, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  validates :title, presence: true, uniqueness: true
  validates :body, presence: true
  validates :address, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :reservations, dependent: :destroy
  has_many :requests, dependent: :destroy
  validates :username, presence: true
  validates :email, presence: true, uniqueness: true
  def self.guest
    find_or_create_by!(email: 'guest01@example.com', username: 'guest', admin: true) do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :admin_user

  def index
  end

  private

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def new
    @request = Request.new
    @rooms = Room.all
    @user = User.find(params[:user_id])
  end

  def index
  end

  def show
  end

  def create
    @user = User.find(params[:user_id])
    @rooms = Room.all
    @request = Request.new(request_params)
    if @request.save
      redirect_to user_path(@user), notice: "リクエストが完了しました"
    else
      flash[:danger] = @request.errors.full_messages
      @request = Request.new(request_params)
      render 'new'
    end
  end

  private

  def request_params
    params.require(:request).permit(:start_date, :end_date, :room_id, :user_id, :customer_name, :email, :phone_number, :message)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  def index
    @reservations = Reservation.all
  end

  def new
    @room = Room.find(params[:room_id])
    @reservation = Reservation.new
    @reservations = Reservation.where(room_id: @room.id)
  end

  def create
    @room = Room.find(params[:room_id])
    @reservations = Reservation.where(room_id: @room.id)
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      session[:reservation] = nil
      redirect_to root_path, notice: "予約が完了しました"
    else
      flash[:danger] = @reservation.errors.full_messages
      @reservation = Reservation.new(reservation_params)
      render 'new'
    end
  end

  def edit
  end

  def show
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :room_id, :user_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to room_path(@room), notice: "更新しました"
    else
      flash[:danger] = @room.errors.full_messages
      @room = Room.new(room_params)
      redirect_to new_admin_room_path
    end
  end

  def destroy
    room = Room.find(params[:id])
    if current_user.admin?
      room.destroy
      redirect_to admin_rooms_path, notice: '部屋を削除しました。'
    end
  end

  def update
    @room = Room.find(params[:id])
    @room.update(room_params)
    if @room.save
      redirect_to room_path(@room), notice: "更新しました"
    else
      flash[:danger] = @room.errors.full_messages
      redirect_to edit_admin_room_path(@room)
    end
  end

  def show
    @room = Room.find(params[:id])
    gon.room = @room
    @reservations = Reservation.where(room_id: params[:id])
  end

  def edit
  end

  private

  def room_params
    params.require(:room).permit(:title, :body, :room_image, :price, :address)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @reservations = Reservation.where(user_id: params[:id])
    @rooms = Room.all
    @requests = Request.where(user_id: params[:id])
  end

  def new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save && current_user.admin == true
      redirect_to admin_users_path
    elsif @user.save
      redirect_to user_path(@user), notice: "更新が完了しました"
    else
      flash[:danger] = @user.errors.full_messages
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました。'
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image, :admin)
  end
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  BASE_TITLE = "SaloShare".freeze

  def full_title(page_title)
    if page_title.blank?
      BASE_TITLE
    else
      "#{page_title} - #{BASE_TITLE}"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1 class="admin_title">管理画面</h1>
  <section class="admin_index">
    <div class="admin_menu">
      <%= link_to admin_rooms_path do %>
        <div class="admin_rooms admins">
          <h3>ルーム管理画面</h3>
        </div>
      <% end %>
      <%= link_to admin_reservations_path do %>
        <div class="admin_reservations admins">
          <h3>予約管理画面</h3>
        </div>
      <% end %>
      <%= link_to admin_users_path do %>
        <div class="admin_users admins">
          <h3>ユーザー管理画面</h3>
        </div>
      <% end %>
    </div>
</section>

app/views/layouts/_alert.html.erb
<% if flash[:notice] %>
  <div class="notification is-info">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="notification is-danger">
    <p class="alert"><%= alert %></p>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footerLeft">
  <h1>SaloShare</h1>
  <p class="c">©︎ RyosukeOnishi</p>
</div>
<div class="footerCenter">
  <div class="footerOpen footerCenterItem">
    <h2>Open</h2>
    <p>9:00~22:00</p>
  </div>
  <div class="footerClose footerCenterItem">
    <h2>Close</h2>
    <p>火曜日</p>
  </div>
</div>
<div class="footerRight">
  <h2>Address</h2>
  <p>兵庫県上野原市下川町平良久貝854</p>
  <p class="c_responsive">©︎ RyosukeOnishi</p>
</div>

app/views/layouts/_header.html.erb
<div class="hamburger">
  <span></span>
  <span></span>
  <span></span>
</div>
<nav class="globalMenuSp">
  <ul class="headerLeft">
    <% if user_signed_in? %>
      <li class="logout">
        <%= link_to "Logout", destroy_user_session_path, method: :delete,  data: {"turbolinks" => false} %>
      </li>
    <% else %>
      <li class="whenLogout">
        <%= link_to "Login", new_user_session_path, data: {"turbolinks" => false} %>
      </li>
      <li>
        <%= link_to "CreateAccount", new_user_registration_path,  data: {"turbolinks" => false} %>
      </li>

    <% end %>
    <li class="navbar-center">
      <%= link_to "rooms", rooms_path,  data: {"turbolinks" => false} %>
    </li>
    <li class="navbar-center">
      <%= link_to "therapists", users_path,  data: {"turbolinks" => false} %>
    </li>

    <% if user_signed_in? && current_user.admin? %>
      <li class="bar_admin">
        <%= link_to "admin", admin_path,  data: {"turbolinks" => false} %>
      </li>
      <li class="navbar-center">
        <%= link_to "mypage", user_path(current_user.id),  data: {"turbolinks" => false} %>
      </li>
    <% elsif user_signed_in? %>
      <li class="navbar-center">
        <%= link_to "mypage", user_path(current_user.id),  data: {"turbolinks" => false} %>
      </li>
    <% end %>
  </ul>
</nav>
<div class="logo">
  <%= link_to root_path, data: {"turbolinks" => false} do %>
    <h1>SaloShare</h1>
  <% end %>
</div>
<% if user_signed_in? && current_user.admin? %>
  <%= link_to admin_path,  data: {"turbolinks" => false} do %>
    <div class="headerRight adminLink">
      <h3 class="headerRightButton">管理画面</h3>
    </div>
  <% end %>
<% elsif user_signed_in? %>
  <%= link_to rooms_path, data: {"turbolinks" => false} do %>
    <div class="headerRight">
      <h3 class="headerRightButton">resavation</h3>
    </div>
  <% end %>
<% else %>
  <%= link_to new_user_registration_path, data: {"turbolinks" => false} do %>
    <div class="headerRight">
      <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= include_gon %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC:300" rel="stylesheet" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <main>
      <%= render 'layouts/alert' %>
      <%= yield %>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/shared/_calendar.html.erb
<%= week_calendar events: reservations do |date, reserve| %>
  <%= date.day %>
  <% reserve.each do |date| %>
    <div class="calendar_time letter_black">
      <p class="calendar_checkin font">
        <%= date.start_date.strftime('%H:%M') %>
      </p>
      <p class="calendar_checkout font">
        <%= date.end_date.strftime('%H:%M') %>
      </p>
      <p>予約済み</p>
    </div>
  <% end %>
<% end %>

app/views/shared/_error_messages.html.erb
<% flash.each do |message_type, messages| %>
  <% messages.each do |message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_month_calendar.html.erb
<%= month_calendar do |date| %>
  <%= date.day %>
<% end %>