config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :rooms do
    resources :reservations
  end
  resources :users do
    resources :requests
  end
  get 'admin', to: 'admin#index'
  namespace :admin do
    resources :rooms
    resources :users
    resources :reservations
  end
end

app/models/room.rb
class Room < ApplicationRecord
  attachment :room_image
  has_many :reservations, dependent: :destroy
  has_many :requests, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  validates :title, presence: true, uniqueness: true
  validates :body, presence: true
  validates :address, presence: true
  validates :price, presence: true
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < ApplicationController
  before_action :admin_user

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to room_path(@room), notice: "更新しました"
    else
      flash[:danger] = @room.errors.full_messages
      redirect_to new_admin_room_path
    end
  end

  def show
    @room = Room.find(params[:id])
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    @room.update(room_params)
    redirect_to room_path(@room)
  end

  def destroy
    room = Room.find(params[:id])
    if current_user.admin?
      room.destroy
      redirect_to admin_rooms_path, notice: '部屋を削除しました。'
    end
  end

  private

  def room_params
    params.require(:room).permit(:title, :body, :room_image, :price, :address)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to room_path(@room), notice: "更新しました"
    else
      flash[:danger] = @room.errors.full_messages
      @room = Room.new(room_params)
      redirect_to new_admin_room_path
    end
  end

  def destroy
    room = Room.find(params[:id])
    if current_user.admin?
      room.destroy
      redirect_to admin_rooms_path, notice: '部屋を削除しました。'
    end
  end

  def update
    @room = Room.find(params[:id])
    @room.update(room_params)
    if @room.save
      redirect_to room_path(@room), notice: "更新しました"
    else
      flash[:danger] = @room.errors.full_messages
      redirect_to edit_admin_room_path(@room)
    end
  end

  def show
    @room = Room.find(params[:id])
    gon.room = @room
    @reservations = Reservation.where(room_id: params[:id])
  end

  def edit
  end

  private

  def room_params
    params.require(:room).permit(:title, :body, :room_image, :price, :address)
  end
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/rooms/_googleMap.html.erb
<script type="text/javascript">
  function initMap() {
    geocoder = new google.maps.Geocoder()
    var test ={lat: gon.room.latitude, lng: gon.room.longitude };
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15,
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                 });
  }
</script>
<script async defer
              src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
</script>
<div id="map"></div>

app/views/rooms/index.html.erb
<article>
  <section>
    <div class="roomsList">
      <h1>ルーム一覧</h1>
    </div>
    <div class="section">
      <div class="container">
        <div class="columns is-multiline">
          <% @rooms.each do |room| %>
            <div class="column is-3">
              <div class="card">
                <div class="card-content">
                  <div class="card-image">
                    <figure>
                      <%= link_to room_path(room) do %>
                        <%= attachment_image_tag room, :room_image, fallback: "4225381_m.jpg", class: "indexProfileImage" %>
                      <% end %>
                    </figure>
                  </div>
                </div>
                <div class="card-content">
                  <div class="media">
                    <div class="media-content">
                      <div class="title text-black"><%=link_to room.title, room_path(room), class: "contentName text-black" %></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</article>

app/views/rooms/show.html.erb
<% provide(:title, @room.title) %>
<article>
  <section>
    <h1><%= @room.title %></h1>
  </section>
  <section class="detailContainer">
    <div class="img">
      <%= attachment_image_tag @room, :room_image, fallback: "4225381_m.jpg", class: "showProfileImage" %>
    </div>
    <aside class="img_detaile">
      <ul class="detaile_list">
        <li class="room_title room_list">
          <h3>部屋名： <%= @room.title %></h3>
        </li>
        <li class="room_address room_list">
          <p>住所： <%= @room.address %></p>
        </li>
        <li class="room_price room_list">
          <p>値段： <%= @room.price %>/1時間</p>
        </li>
        <li class="room_body">
          <p>
            特徴・備品等<br>
            <% if @room.body != nil %>
              <span><%= safe_join(@room.body.split("\n"),tag(:br)) %></span>
            <% end %>
          </p>
        </li>
        <li>
          <button class="button backWhite"><%= link_to "予約", new_room_reservation_path(@room), {class: "black"} %></button>
        </li>
      </ul>
    </aside>
  </section>

  <section class="calender">
    <%= render 'shared/calendar', reservations: @reservations %>
  </section>
  <section>
    <%= render 'rooms/googleMap', room: @room %>
  </section>
</article>