config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :rooms do
    resources :reservations
  end
  resources :users do
    resources :requests
  end
  get 'admin', to: 'admin#index'
  namespace :admin do
    resources :rooms
    resources :users
    resources :reservations
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :reservations, dependent: :destroy
  has_many :requests, dependent: :destroy
  validates :username, presence: true
  validates :email, presence: true, uniqueness: true
  def self.guest
    find_or_create_by!(email: 'guest01@example.com', username: 'guest', admin: true) do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    user = User.find(params[:id])
    if current_user.admin?
      user.destroy
      redirect_to admin_users_path, notice: 'ユーザーを削除しました。'
    end
  end

  private

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @reservations = Reservation.where(user_id: params[:id])
    @rooms = Room.all
    @requests = Request.where(user_id: params[:id])
  end

  def new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save && current_user.admin == true
      redirect_to admin_users_path
    elsif @user.save
      redirect_to user_path(@user), notice: "更新が完了しました"
    else
      flash[:danger] = @user.errors.full_messages
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました。'
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image, :admin)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h2>管理画面　ユーザー編集</h2>
<section class="section">
  <div class="detailContainer">
    <div class="img">
      <%= attachment_image_tag @user, :profile_image, fallback: "4225381_m.jpg", class: "showProfileImage" %>
    </div>
    <aside class="img_detaile">
      <h3><%= @user.username %></h3>
      <p><%= @user.profile %></p>
      <%= form_for @user do |f| %>
        <div class="field">
          <%= f.label :admin, "admin権限", class: "label" %>
          <%= f.check_box :admin, autofocus: true %>
        </div>
        <%= f.submit "更新", class: "button" %>
      <% end %>
    </aside>
  </div>
</section>

app/views/admin/users/index.html.erb
<h2>管理画面　ユーザー一覧</h2>
<section class="admin_user_index">
  <table border="1" class="index_table">
    <tr class="user_header">
      <th>id</th>
      <th>name</th>
      <th>email</th>
      <th>created_at</th>
      <th>admin</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
    <% @users.each do |user| %>
      <tr class="admin_users">
        <th><%= user.id %></th>
        <th><%= user.username %></th>
        <th><%= user.email %></th>
        <th><%= user.created_at.strftime("%m月%d日%H時%M分") %></th>
        <th><%= user.admin %></th>
        <th><%= link_to edit_admin_user_path(user), class: "table_edit" do %>編集<% end %></th>
        <th><%= link_to '削除', admin_user_path(user.id), method: :delete, class: "black" %></th>
      </tr>
    <% end %>
  </table>
</section>